### ISSUE TITLE
Module not found: Error: Can't resolve 'posthtml-loader' in '<absolute path>'

### ISSUE THREAD

**Issue by jrencz** [posthtml/posthtml-loader#117]
After installing `postcss-loader@1.0.0` I started getting errors that make my webpack build fail.

### `📝  Details`

Module not found: Error: Can't resolve 'posthtml-loader' in '<absolute path>'

|OS|node|npm/yarn|package|
|:-:|:--:|:-:|:------:|
|macOS 10.13.1|8.9.1|npm 5.5.1|1.0.0|

Installed `postcss-loader@1.0.0` has `main` field in `package.json` set to `index.js` which doesn't exist.
Versions <1 had explicit `main`. Version `1.0.0` only has `files` which doesn't seem to be enough for webpack.

Adding `"main": "lib"` resolves the issue

**Comment by michael-ciniawsky** [comment]
Fixed in efa672e95537a98c4a2af7ea5d294511c23db373
Released in [v1.0.1](https://github.com/posthtml/posthtml-loader/releases/tag/v1.0.1) 🎉

**Comment by jrencz** [comment]
Works fine, thx
