### ISSUE TITLE
Jade filename issue

### ISSUE THREAD

**Issue by jescalan** [posthtml/posthtml-loader#4]
Ok so this is a strange issue, and I'm not entirely sure how to go about solving it honestly, but will try to clearly explain it and see what you guys think.

I'm using posthtml with the jade plugin through this loader in webpack. My jade template uses an include, which the jade parser attempt to read in order to make it work. However jade it requires you to pass [a `filename` option](https://github.com/posthtml/posthtml-jade#options) for each file so that it is able to resolve the path to any includes and read them correctly.

When using this loader, you configure it once upfront, and each file is loaded in by webpack, so there in no way to set the `filename` option accurately. Therefore it fails whenever you need to use an extend, include, etc.

I'm filing this here instead of in posthtml-jade because that plugin isn't the issue, it accept the `filename` option just fine if you pass it in. The issue is that there needs to be some way to pass the filename on a per-file basis as files are pushed through the posthtml-loader.

I took a quick look at the code for each of these libraries and it seems like this is not going to be simple. Any thoughts on how we could potentially resolve this?

**Comment by jescalan** [comment]
Ok I have a slight lead on how this might be possible to pull off. Since you guys pass the loader context through when using a function as a config value, you can get the filename off the loader context. However, at this point the plugins are already initialized and the options are set. That being said, if there was a way to pass override options the the initialized plugin [here](https://github.com/posthtml/posthtml-jade/blob/master/index.js#L21), I *think* this would work. I'm going to test this, and if it does I'll make a PR into the jade plugin and close this out.

**Comment by jescalan** [comment]
Ah never mind, you can just pass the filename when you initialize the plugin in the webpack config. For the record, this is how it looks:

```js
// webpack.config.js
const jadePlugin = require('posthtml-jade')

{
  posthtml: (ctx) => {
    const path = url.parse(ctx.request.split('!').slice(-1)[0]).pathname
    return defaults: [jadePlugin({ filename: path })]
  }
}
```

Just tested this and confirmed working. Thanks for being my rubber duck, github issues 🐣

**Comment by michael-ciniawsky** [comment]
I add it to the README in 1.0.0, but currently i'm finishing the common config for posthtml to make auto option/plugin/preset loading working.

**Comment by jescalan** [comment]
@michael-ciniawsky If you want me to PR it in anywhere I'd be happy to, just let me know what you're looking for and where 😁

**Comment by michael-ciniawsky** [comment]
:+1 sure, when you please add it under #Usage Setup code example in the README, something like Setup with File Context/Path (but call it whatever you like :)), and don't forget to add yourself as a contributor above the LICENSE, e.g like it's done in [posthtml-load-plugins](https://github.com/posthtml/posthtml-load-plugins).

This is really appreciated, it will be very useful for posthtml-exp, posthtml-modules etc. You saved me a headache :D.

```txt
|––module
|    |––index.{html,jade,sml}
|    |––index.json
|
|––webpack.config.js
```

```html
<div class={{class}}>{{content}}</div>
```

```json
{
  "class": "app",
  "content": "Hello World!"
}
```

```html
<div class="app">Hello World!</div>
```

I will reopen the issue while waiting for/approving the PR. Take your time...:)
