### ISSUE TITLE
There are no tests?

### ISSUE THREAD

**Issue by jescalan** [posthtml/posthtml-loader#6]
Do you want me to add some tests? I'd be happy to, I think it would be a pretty nice benefit for this module...

**Comment by GitScrum** [comment]
@jescalan  welcome a PR )

**Comment by michael-ciniawsky** [comment]
@jescalan I currently quite busy in everyday babylon circus, i want to add posthtml-load-config in before 1.0 to the loader and th e first major release will be tested of course, you can write some if you want but don't waste your spare time if you find something better at your hands :)
