### ISSUE TITLE
Is there a good way of injecting variables into HTML?

### ISSUE THREAD

**Issue by couturecraigj** [posthtml/posthtml-loader#74]
I really like the idea of breaking HTML out to be parsed and rendered by a javascript tool, so Kudos.  I am wondering if one could integrate variables using `posthtml` in the loader though?  Does this seem like a possibility.  To give context what I am thinking of doing is to load an MJML template but to have `{{}}` syntax for the expression loader to enable personalized templates per users and would love to pass that in using the `require()` statement.  I am trying to get my head around webpack and sometimes find myself confused so if there is anything you can suggest please assist.

**Comment by jescalan** [comment]
So I think in order to do what you are asking about, posthtml would need to be able to generate a function that would be able to add variables at runtime. At the moment, posthtml does not have this feature, so I wasn't able to add it to the loader. You can try [reshape](https://github.com/reshape/loader) if you need this specific functionality though, it's very similar to posthtml but generates functions that are client-compatible rather than only html as a string.

**Comment by michael-ciniawsky** [comment]
@couturecraigj `v1.0.0`  is on the finish line, templates (ES2015) are possible then

**webpack.config.js**
```js
{
   loader: 'posthtml-loader', options: { template: true } 
  // ..., options { template: '$' } '$' === Your custom placeholder, default atm '_'
}
```
```html
<div>${ _.hello }</div>
```
```js
import template from './template'

template({ hello: 'Hello World!' })
```

Maybe an option to include a runtime, but I don't think so ES2015 template literals && posthtml-expressions will do the job 😛 

Reshape is also a good option, you can take a look into

**Comment by couturecraigj** [comment]
Wow, thanks for the fast response.  I think I like the template literals
example but is there a way to force webpack to render these strings using
the template literals syntax do you know?  Maybe this is a question for
another board but I would not even know which one to post it to.

**Comment by michael-ciniawsky** [comment]
@couturecraigj Can you give a small example what you excatly mean by that 😛 ?

**Comment by michael-ciniawsky** [comment]
@couturecraigj You can try it out by installing from git directly 

**package.json**
```json
{
  "devDependencies": {
      "posthtml-loader": "posthtml/posthtml-loader"
   }
}
```

**Comment by couturecraigj** [comment]
@michael-ciniawsky oh wow,

Either it did not show up on my email or when you edited it you added the example... That looks perfect.  That would be even better than even linking posthtml-expressions.  That would make this definitely fit many of my needs.  Many template systems seem to have non-minified states so I would like to reduce their size as much as possible.  Love what you guys are doing and thanks for the fast responses.
